# tests/test_notebook.py
"""Tests for Jupyter notebook job type (Phase 5)."""
from pathlib import Path
import pytest


# ── Task defaults ─────────────────────────────────────────────────────────────

def test_notebook_in_task_defaults():
    from iitgpu.jobs import TASK_DEFAULTS
    assert "notebook" in TASK_DEFAULTS


def test_notebook_defaults_correct():
    from iitgpu.jobs import resource_defaults
    d = resource_defaults("notebook")
    assert d.gpus == 1
    assert d.cpus == 8
    assert d.mem_gb == 32
    assert d.time_limit == "08:00:00"


# ── render_notebook_sbatch ────────────────────────────────────────────────────

def _nb_spec(**kwargs):
    from iitgpu.jobs import JobSpec
    defaults = dict(
        job_name="notebook",
        partition="gpu",
        gpus=1,
        cpus=8,
        mem_gb=32,
        time_limit="08:00:00",
        run_command="",
        task_type="notebook",
    )
    defaults.update(kwargs)
    return JobSpec(**defaults)


def test_notebook_sbatch_has_jupyter_launch(tmp_path):
    from iitgpu.jobs import make_job_folder, render_notebook_sbatch
    spec = _nb_spec()
    folder = make_job_folder(str(tmp_path), spec)
    script = render_notebook_sbatch(spec, folder, port=8888)
    assert "jupyter lab" in script
    assert "--no-browser" in script
    assert "--ip=$IIT_NODE_ADDR" in script
    assert "--port=8888" in script


def test_notebook_sbatch_binds_to_node_addr_not_loopback(tmp_path):
    """The notebook runs on a GPU compute node but users tunnel in through the
    login/gateway node — a *different* host. Binding to 127.0.0.1 (loopback)
    made Jupyter unreachable through the tunnel. It must bind to the node's
    SLURM NodeAddr (routable from the gateway) and forward the tunnel there,
    never to loopback or the public-facing 0.0.0.0."""
    from iitgpu.jobs import make_job_folder, render_notebook_sbatch
    spec = _nb_spec()
    folder = make_job_folder(str(tmp_path), spec)
    script = render_notebook_sbatch(spec, folder, port=8888)
    # Resolves the node's reachable address at runtime …
    assert "IIT_NODE_ADDR=" in script
    assert "NodeAddr=" in script
    # … binds the server to it …
    assert "--ip=$IIT_NODE_ADDR" in script
    # … and the tunnel forwards to that address, not localhost.
    assert "-L 8888:$IIT_NODE_ADDR:8888" in script
    # Never exposed on all interfaces (public network).
    assert "0.0.0.0" not in script


def test_notebook_sbatch_prints_ssh_tunnel_hint(tmp_path):
    from iitgpu.jobs import make_job_folder, render_notebook_sbatch
    spec = _nb_spec()
    folder = make_job_folder(str(tmp_path), spec)
    script = render_notebook_sbatch(spec, folder, port=8888,
                                    gateway_host="10.35.4.100", gateway_port=2225)
    assert "ssh" in script
    assert "10.35.4.100" in script
    assert "8888" in script
    assert "2225" in script


def test_notebook_sbatch_token_generated_at_runtime(tmp_path):
    from iitgpu.jobs import make_job_folder, render_notebook_sbatch
    spec = _nb_spec()
    folder = make_job_folder(str(tmp_path), spec)
    script = render_notebook_sbatch(spec, folder)
    # Token must be generated by the job, not hardcoded in the script
    assert "JUPYTER_TOKEN" in script
    assert "secrets.token_hex" in script


def test_notebook_sbatch_uses_conda_env(tmp_path):
    from iitgpu.jobs import make_job_folder, render_notebook_sbatch
    spec = _nb_spec(conda_env="/shared/envs/pytorch-2.7")
    folder = make_job_folder(str(tmp_path), spec)
    script = render_notebook_sbatch(spec, folder)
    assert "conda activate" in script
    assert "jupyter lab" in script


def test_notebook_sbatch_uses_container_image(tmp_path):
    from iitgpu.jobs import make_job_folder, render_notebook_sbatch
    spec = _nb_spec(container_image="/shared/images/data-science.sif")
    folder = make_job_folder(str(tmp_path), spec)
    script = render_notebook_sbatch(spec, folder)
    assert "apptainer exec --nv" in script
    assert "jupyter lab" in script
    assert "conda activate" not in script


def test_notebook_sbatch_custom_port(tmp_path):
    from iitgpu.jobs import make_job_folder, render_notebook_sbatch
    spec = _nb_spec()
    folder = make_job_folder(str(tmp_path), spec)
    script = render_notebook_sbatch(spec, folder, port=9000)
    assert "--port=9000" in script
    assert "9000" in script   # also appears in tunnel hint


def test_notebook_sbatch_has_sbatch_directives(tmp_path):
    from iitgpu.jobs import make_job_folder, render_notebook_sbatch
    spec = _nb_spec()
    folder = make_job_folder(str(tmp_path), spec)
    script = render_notebook_sbatch(spec, folder)
    assert "#!/bin/bash" in script
    assert "#SBATCH --gres=gpu:1" in script
    assert "#SBATCH --mem=32G" in script
    assert "#SBATCH --time=08:00:00" in script


def test_notebook_sbatch_self_heals_missing_jupyter(tmp_path):
    """A chosen env without JupyterLab must self-heal, not die with
    'jupyter: command not found' (the original notebook-job failure)."""
    from iitgpu.jobs import make_job_folder, render_notebook_sbatch
    spec = _nb_spec(conda_env="/shared/envs/pytorch-2.7")
    folder = make_job_folder(str(tmp_path), spec)
    script = render_notebook_sbatch(spec, folder)
    assert "command -v jupyter" in script
    assert "pip install --user" in script and "jupyterlab" in script
    # The launch still happens after the guard.
    assert script.index("command -v jupyter") < script.index("jupyter lab")


def test_notebook_sbatch_no_self_heal_for_container(tmp_path):
    """Container images are expected to ship Jupyter; no pip self-heal there."""
    from iitgpu.jobs import make_job_folder, render_notebook_sbatch
    spec = _nb_spec(container_image="/shared/images/data-science.sif")
    folder = make_job_folder(str(tmp_path), spec)
    script = render_notebook_sbatch(spec, folder)
    assert "pip install --user --quiet jupyterlab" not in script


def test_notebook_sbatch_emits_mail_directives_when_mail_user_set(tmp_path):
    from iitgpu.jobs import make_job_folder, render_notebook_sbatch
    spec = _nb_spec(mail_user="dahamadmin@iit.ac.lk")
    folder = make_job_folder(str(tmp_path), spec)
    script = render_notebook_sbatch(spec, folder)
    assert "#SBATCH --mail-user=dahamadmin@iit.ac.lk" in script
    assert "#SBATCH --mail-type=" in script


def test_notebook_sbatch_no_mail_directives_without_mail_user(tmp_path):
    from iitgpu.jobs import make_job_folder, render_notebook_sbatch
    spec = _nb_spec()
    folder = make_job_folder(str(tmp_path), spec)
    script = render_notebook_sbatch(spec, folder)
    assert "--mail-user" not in script


def test_tensorboard_sbatch_emits_mail_directives_when_mail_user_set(tmp_path):
    from iitgpu.jobs import JobSpec, make_job_folder, render_tensorboard_sbatch
    spec = JobSpec(job_name="tensorboard", partition="gpu", gpus=0, cpus=2,
                   mem_gb=8, time_limit="08:00:00", run_command="",
                   task_type="tensorboard", mail_user="dahamadmin@iit.ac.lk")
    folder = make_job_folder(str(tmp_path), spec)
    script = render_tensorboard_sbatch(spec, folder, "/shared/logs")
    assert "#SBATCH --mail-user=dahamadmin@iit.ac.lk" in script
    assert "#SBATCH --mail-type=" in script
